name: fastlane_screenshot_automation
description: Helper to setup fastlane on both android and ios projects
version: 0.0.4
repository: https://github.com/BenjaminRA/fastlane_screenshot_automation

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  args: ^2.3.1
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
